name: Swift Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Set up Xcode (corresponding to visionOS support)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

  swiftlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
