name: Swift Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Set up Xcode (corresponding to visionOS support)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'
          
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SwiftLint
        run: |
          wget https://github.com/realm/SwiftLint/releases/download/0.43.1/swiftlint_linux.zip
          unzip swiftlint_linux.zip
          sudo mv swiftlint /usr/local/bin/
      - name: Run SwiftLint
        run: swiftlint

