name: Swift Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode (corresponding to visionOS support)
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3' 
        
    - name: Build and Test
      run: |
        xcodebuild build-for-testing \
          -scheme "UmainSpatialGestures" \
          -sdk visionossimulator \
          -destination 'platform=visionOS Simulator,name=Apple Vision Pro'
        xcodebuild test-without-building \
          -scheme "UmainSpatialGestures" \
          -sdk visionossimulator \
          -destination 'platform=visionOS Simulator,name=Apple Vision Pro'



